[package]
name = "blink_screen"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.9"
winit = { version = "0.29", features = ["rwh_05"]}
raw-window-handle = "0.6"
web-sys = { version = "0.3.64", features = ["GpuBufferUsage"] }	